version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: recipesdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_HOST: db    
      DB_NAME: recipesdb
      DB_PASSWORD: 123456
      DB_PORT: 5432
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm start

  frontend:
    build: ./frontend 
    container_name: frontend_container
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    environment:
    - CHOKIDAR_USEPOLLING=true
    - HOST=0.0.0.0 
    env_file:
    - ./frontend/.env

volumes:
  db_data:
